//
//  SampleData.swift
//  Shamchiroq
//
//  Created by Bakhtiyorjon Mirzajonov on 1/6/24.
//

import Foundation

class SampleData: ObservableObject {
    static let shared = SampleData()
    
    init() {
        initializeData()
    }
    
    var users: [User] = []
    var reviews: [Review] = []
    var ratings: [Rating] = []
    var books: [Book] = []
    
    func initializeData() {
        users = [
            User(firstName: "John", lastName: "Doe", username: "john_doe", email: "john@example.com", image: "Elon Musk"),
            User(firstName: "Jane", lastName: "Smith", username: "jane_smith", email: "jane@example.com", image: "Bill Gates"),
            User(firstName: "Alice", lastName: "Johnson", username: "alice_j", email: "alice@example.com", image: "Joe Rogan"),
            User(firstName: "Bob", lastName: "Williams", username: "bob_w", email: "bob@example.com", image: "no-image"),
            User(firstName: "Eva", lastName: "Brown", username: "eva_brown", email: "eva@example.com", image: "no-image"),
            User(firstName: "Charlie", lastName: "Johnson", username: "charlie_j", email: "charlie@example.com", image: "no-image"),
            User(firstName: "Sophia", lastName: "Miller", username: "sophia_m", email: "sophia@example.com", image: "no-image"),
            User(firstName: "David", lastName: "Davis", username: "david_d", email: "david@example.com", image: "no-image"),
            User(firstName: "Emma", lastName: "Jones", username: "emma_j", email: "emma@example.com", image: "no-image"),
            User(firstName: "Michael", lastName: "Taylor", username: "michael_t", email: "michael@example.com", image: "no-image"),
        ]
        
        reviews = [
            Review(user: users[0], body: "Great book!"),
            Review(user: users[1], body: "Enjoyed it!"),
            Review(user: users[2], body: "Interesting plot!"),
            Review(user: users[3], body: "Could be better."),
            Review(user: users[4], body: "A must-read!"),
            Review(user: users[5], body: "Didn't like the ending."),
            Review(user: users[6], body: "Captivating story!"),
            Review(user: users[7], body: "Highly recommended."),
            Review(user: users[8], body: "Well-written."),
            Review(user: users[9], body: "Could not put it down!"),
        ]
        
        ratings = [
            Rating(user: users[0], numOfStars: 4),
            Rating(user: users[1], numOfStars: 5),
            Rating(user: users[2], numOfStars: 3),
            Rating(user: users[3], numOfStars: 2),
            Rating(user: users[4], numOfStars: 5),
            Rating(user: users[5], numOfStars: 3),
            Rating(user: users[6], numOfStars: 4),
            Rating(user: users[7], numOfStars: 5),
            Rating(user: users[8], numOfStars: 4),
            Rating(user: users[9], numOfStars: 5),
        ]
        
        books = [
            Book(title: "The Great Gatsby", author: "F. Scott Fitzgerald", image: "The-Great-Gatsby", ratings: [ratings[0], ratings[1]], reviews: [reviews[0], reviews[1]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "To Kill a Mockingbird", author: "Harper Lee", image: "no-book-image", ratings: [ratings[2], ratings[3]], reviews: [reviews[2], reviews[3]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "1984", author: "George Orwell", image: "no-book-image", ratings: [ratings[4], ratings[5]], reviews: [reviews[4], reviews[5]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "Pride and Prejudice", author: "Jane Austen", image: "no-book-image", ratings: [ratings[6], ratings[7]], reviews: [reviews[6], reviews[7]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Catcher in the Rye", author: "J.D. Salinger", image: "no-book-image", ratings: [ratings[8], ratings[9]], reviews: [reviews[8], reviews[9]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Lord of the Rings", author: "J.R.R. Tolkien", image: "no-book-image", ratings: [ratings[6], ratings[1]], reviews: [reviews[6], reviews[9]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "Harry Potter and the Sorcerer's Stone", author: "J.K. Rowling", image: "no-book-image", ratings: [ratings[2], ratings[3]], reviews: [reviews[9], reviews[1]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Hobbit", author: "J.R.R. Tolkien", image: "no-book-image", ratings: [ratings[1], ratings[5]], reviews: [reviews[4], reviews[5]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Great Book", author: "John Doe", image: "no-book-image", ratings: [ratings[6], ratings[7]], reviews: [reviews[6], reviews[7]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "Fantastic Novel", author: "Alice Smith", image: "no-book-image", ratings: [ratings[8], ratings[9]], reviews: [reviews[8], reviews[9]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "Mystery Thriller", author: "Bob Johnson", image: "no-book-image", ratings: [ratings[0], ratings[1]], reviews: [reviews[0], reviews[1]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Chronicles of Narnia", author: "C.S. Lewis", image: "no-book-image", ratings: [ratings[2], ratings[3]], reviews: [reviews[2], reviews[3]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "Brave New World", author: "Aldous Huxley", image: "no-book-image", ratings: [ratings[4], ratings[5]], reviews: [reviews[4], reviews[5]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "One Hundred Years of Solitude", author: "Gabriel García Márquez", image: "no-book-image", ratings: [ratings[6], ratings[7]], reviews: [reviews[6], reviews[7]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Da Vinci Code", author: "Dan Brown", image: "no-book-image", ratings: [ratings[8], ratings[9]], reviews: [reviews[8], reviews[9]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Alchemist", author: "Paulo Coelho", image: "no-book-image", ratings: [ratings[3], ratings[1]], reviews: [reviews[6], reviews[1]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Shining", author: "Stephen King", image: "no-book-image", ratings: [ratings[2], ratings[3]], reviews: [reviews[2], reviews[3]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Hunger Games", author: "Suzanne Collins", image: "no-book-image", ratings: [ratings[4], ratings[5]], reviews: [reviews[4], reviews[5]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Kite Runner", author: "Khaled Hosseini", image: "no-book-image", ratings: [ratings[6], ratings[7]], reviews: [reviews[6], reviews[7]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
            Book(title: "The Fault in Our Stars", author: "John Green", image: "no-book-image", ratings: [ratings[8], ratings[9]], reviews: [reviews[8], reviews[9]], description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tortor posuere ac ut consequat semper viverra. Feugiat in fermentum posuere urna nec tincidunt praesent. Blandit libero volutpat sed cras. Aliquam etiam erat velit scelerisque in. Volutpat sed cras ornare arcu dui vivamus arcu. Morbi tincidunt ornare massa eget egestas purus viverra. Leo integer malesuada nunc vel risus commodo viverra maecenas. Mauris sit amet massa vitae tortor condimentum lacinia quis vel. Nam libero justo laoreet sit amet cursus. Lacinia at quis risus sed vulputate odio. Ut aliquam purus sit amet luctus venenatis. Volutpat diam ut venenatis tellus in metus vulputate eu. Massa placerat duis ultricies lacus. Urna neque viverra justo nec ultrices dui. Eu non diam phasellus vestibulum lorem sed. Pharetra convallis posuere morbi leo urna molestie at. Facilisis volutpat est velit egestas dui id ornare. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt."),
        ]
    }
}
